import type { BloodlineDefinition, EnemyDefinition, ItemDefinition, ModeConfig, QuestDefinition, RankDefinition, Rank, SkillDefinition, SpinConfig } from './types';

export const SAVE_VERSION = 3;
export const MD_REGEN_BASE = 5;

/** Display names for ranks (Naruto theme) */
export const RANK_DISPLAY: Record<Rank, string> = {
  E: '下忍 (Genin)',
  D: '中忍 (Chunin)',
  C: '上忍 (Jonin)',
};

/** Paid rest costs by level bracket */
export const CLINIC_COSTS: { maxLevel: number; cost: number }[] = [
  { maxLevel: 10, cost: 50 },
  { maxLevel: 20, cost: 120 },
  { maxLevel: 30, cost: 250 },
];

export const SKILLS: Record<string, SkillDefinition> = {
  BLAZE_SHOT: {
    id: 'BLAZE_SHOT',
    name: '火遁・豪火球之術',
    description: '發射強大火球，造成火屬性傷害並可能引燃目標。',
    hpCost: 0,
    mdCost: 15,
    cooldownTurn: 2,
    requiredLevel: 1,
    effects: {
      damageMultiplier: 1.5,
      burnChance: 0.4,
      burnDamagePerTurn: 5,
      burnDuration: 3,
    },
  },
  THUNDER_STRIKE: {
    id: 'THUNDER_STRIKE',
    name: '雷切 (Chidori)',
    description: '以閃電凝聚於手，貫穿敵人，造成巨大雷屬性傷害。',
    hpCost: 0,
    mdCost: 30,
    cooldownTurn: 4,
    requiredLevel: 8,
    effects: {
      damageMultiplier: 2.5,
    },
  },
  VOID_SLASH: {
    id: 'VOID_SLASH',
    name: '萬花筒寫輪眼・天照',
    description: '以黑炎焚盡一切，消耗 HP 和 Chakra 換取極致破壞力。',
    hpCost: 20,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 12,
    effects: {
      damageMultiplier: 3.0,
    },
  },
  IRON_GUARD: {
    id: 'IRON_GUARD',
    name: '八卦六十四掌・防禦',
    description: '以八卦掌封閉經脈，進入守護姿態，回復 15% HP。',
    hpCost: 0,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 3,
    effects: {
      damageMultiplier: 0,
      healSelfPercent: 0.15,
    },
  },
  MIST_STEP: {
    id: 'MIST_STEP',
    name: '水遁・霧隱術',
    description: '隱身濃霧中發動奇襲，回復 20 Chakra。',
    hpCost: 0,
    mdCost: 25,
    cooldownTurn: 3,
    requiredLevel: 5,
    effects: {
      damageMultiplier: 1.2,
      mdRestore: 20,
    },
  },
  WATER_DRAGON: {
    id: 'WATER_DRAGON',
    name: '水遁・水龍彈術',
    description: '召喚水龍衝擊敵人，造成強力水屬性傷害。',
    hpCost: 0,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 2,
    effects: { damageMultiplier: 2.0 },
  },
  SAND_ARMOR: {
    id: 'SAND_ARMOR',
    name: '砂瀑防護盾',
    description: '以砂包覆全身形成防護盾，回復 25% HP。',
    hpCost: 0,
    mdCost: 25,
    cooldownTurn: 4,
    requiredLevel: 4,
    effects: { damageMultiplier: 0, healSelfPercent: 0.25 },
  },
  LIGHTNING_CLONE: {
    id: 'LIGHTNING_CLONE',
    name: '雷遁・影分身',
    description: '以雷電創造分身猛攻，有機率對敵人造成灼燒。',
    hpCost: 0,
    mdCost: 25,
    cooldownTurn: 3,
    requiredLevel: 6,
    effects: { damageMultiplier: 1.8, burnChance: 0.30, burnDamagePerTurn: 6, burnDuration: 3 },
  },
  EARTH_SPIKE: {
    id: 'EARTH_SPIKE',
    name: '土遁・土流牆',
    description: '從地底升起巨大土牆衝擊敵人，造成大量傷害。',
    hpCost: 0,
    mdCost: 30,
    cooldownTurn: 4,
    requiredLevel: 10,
    effects: { damageMultiplier: 2.2 },
  },
  WIND_SLASH: {
    id: 'WIND_SLASH',
    name: '風遁・風刃術',
    description: '以風刃高速斬擊敵人，速度極快難以閃避。',
    hpCost: 0,
    mdCost: 18,
    cooldownTurn: 2,
    requiredLevel: 3,
    effects: { damageMultiplier: 1.6 },
  },
  SHADOW_BIND: {
    id: 'SHADOW_BIND',
    name: '影縫之術',
    description: '以影子束縛敵人，並趁機吸收查克拉。',
    hpCost: 0,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 5,
    effects: { damageMultiplier: 1.4, mdRestore: 15 },
  },
  BONE_LANCE: {
    id: 'BONE_LANCE',
    name: '屍骨脈・骨矛',
    description: '以自身骨骼為矛貫穿敵人，消耗 HP 換取毀滅性傷害。',
    hpCost: 20,
    mdCost: 25,
    cooldownTurn: 4,
    requiredLevel: 15,
    effects: { damageMultiplier: 2.8 },
  },
};

export const BLOODLINES: Record<string, BloodlineDefinition> = {
  BLAZE: {
    id: 'BLAZE',
    name: '不知火一族（火遁）',
    rarity: 'COMMON',
    description: '擁有強大火遁血統，天生攻擊力提升。',
    passive: { atkMultiplier: 1.1 },
    skillIds: ['BLAZE_SHOT'],
  },
  STORM: {
    id: 'STORM',
    name: '日向一族（白眼）',
    rarity: 'RARE',
    description: '白眼洞察一切弱點，提升暴擊機率。',
    passive: { critChanceBonus: 0.1 },
    skillIds: ['THUNDER_STRIKE'],
  },
  VOID: {
    id: 'VOID',
    name: '宇智波一族（寫輪眼）',
    rarity: 'LEGENDARY',
    description: '寫輪眼賦予極致力量，但以生命力為代價。',
    passive: { atkMultiplier: 1.4, hpMultiplier: 0.8 },
    skillIds: ['VOID_SLASH'],
  },
  IRON: {
    id: 'IRON',
    name: '山中一族（鐵壁防禦）',
    rarity: 'COMMON',
    description: '山中一族的堅韌血脈，提供卓越防禦能力。',
    passive: { defMultiplier: 1.25 },
    skillIds: ['IRON_GUARD'],
  },
  MIST: {
    id: 'MIST',
    name: '霧隱一族（霧步）',
    rarity: 'RARE',
    description: '霧隱忍者的血統，速度與 Chakra 回復俱佳。',
    passive: { spdBonus: 2, mdRegenBonus: 5 },
    skillIds: ['MIST_STEP'],
  },
  WATER: {
    id: 'WATER',
    name: '水之國族（水遁）',
    rarity: 'COMMON',
    description: '水之國的血統，查克拉回復能力優異。',
    passive: { mdRegenBonus: 8 },
    skillIds: ['WATER_DRAGON'],
  },
  SAND: {
    id: 'SAND',
    name: '砂之國族（防禦）',
    rarity: 'RARE',
    description: '砂隱村的防禦血統，鐵壁之守護。',
    passive: { defMultiplier: 1.3, spdBonus: 1 },
    skillIds: ['SAND_ARMOR'],
  },
  LIGHTNING_BL: {
    id: 'LIGHTNING_BL',
    name: '雲之村族（雷遁）',
    rarity: 'RARE',
    description: '雲隱村的雷遁血統，攻擊力與暴擊俱佳。',
    passive: { atkMultiplier: 1.2, critChanceBonus: 0.05 },
    skillIds: ['LIGHTNING_CLONE'],
  },
  EARTH: {
    id: 'EARTH',
    name: '岩之村族（土遁）',
    rarity: 'COMMON',
    description: '岩隱村的土遁血統，生命力強韌。',
    passive: { hpMultiplier: 1.2 },
    skillIds: ['EARTH_SPIKE'],
  },
  WIND: {
    id: 'WIND',
    name: '風之國族（風遁）',
    rarity: 'COMMON',
    description: '風之國的風遁血統，速度超群。',
    passive: { spdBonus: 3 },
    skillIds: ['WIND_SLASH'],
  },
  SHADOW: {
    id: 'SHADOW',
    name: '奈良一族（影術）',
    rarity: 'RARE',
    description: '奈良一族的影術血統，智謀與攻擊兼備。',
    passive: { atkMultiplier: 1.15, critChanceBonus: 0.08 },
    skillIds: ['SHADOW_BIND'],
  },
  KAGUYA: {
    id: 'KAGUYA',
    name: '鬼燈一族（骨遁）',
    rarity: 'LEGENDARY',
    description: '鬼燈一族的骨遁血統，攻擊力強大但以生命力為代價。',
    passive: { atkMultiplier: 1.45, hpMultiplier: 0.85 },
    skillIds: ['BONE_LANCE'],
  },
};

export const SPIN_CONFIG: SpinConfig = {
  priceRyo: 100,
  entries: [
    { bloodlineId: 'BLAZE', baseWeight: 50 },
    { bloodlineId: 'IRON', baseWeight: 50 },
    { bloodlineId: 'WATER', baseWeight: 50 },
    { bloodlineId: 'EARTH', baseWeight: 45 },
    { bloodlineId: 'WIND', baseWeight: 45 },
    { bloodlineId: 'STORM', baseWeight: 20 },
    { bloodlineId: 'MIST', baseWeight: 18 },
    { bloodlineId: 'SAND', baseWeight: 18 },
    { bloodlineId: 'LIGHTNING_BL', baseWeight: 15 },
    { bloodlineId: 'SHADOW', baseWeight: 15 },
    { bloodlineId: 'VOID', baseWeight: 5 },
    { bloodlineId: 'KAGUYA', baseWeight: 4 },
  ],
};

export const MODE_CONFIG: ModeConfig = {
  requiredLevel: 10,
  requireAnyBloodline: true,
  atkMultiplier: 1.5,
  defMultiplier: 1.2,
  instantHealPercent: 0.2,
  mdCostPerTurn: 10,
};

export const ENEMIES: Record<string, EnemyDefinition> = {
  TRAINING_DUMMY: {
    id: 'TRAINING_DUMMY',
    name: '替身木樁',
    description: '忍者學校的訓練用替身木樁。',
    stats: { maxHp: 50, atk: 5, def: 2, spd: 1 },
  },
  FOREST_WOLF: {
    id: 'FOREST_WOLF',
    name: '追蹤忍犬',
    description: '木葉村的追蹤忍犬，速度迅猛。',
    stats: { maxHp: 70, atk: 9, def: 3, spd: 6 },
  },
  BANDIT_CHIEF: {
    id: 'BANDIT_CHIEF',
    name: '音忍刺客',
    description: '大蛇丸麾下的音忍刺客，善於蓄力猛攻。',
    stats: { maxHp: 100, atk: 14, def: 4, spd: 3 },
    specialAbility: 'CHARGE',
    specialAbilityChance: 0.25,
  },
  ELITE_NINJA: {
    id: 'ELITE_NINJA',
    name: '暗部隊員',
    description: '木葉暗部的精銳成員，實力深不可測。',
    stats: { maxHp: 140, atk: 17, def: 6, spd: 7 },
  },
  MOUNTAIN_BEAR: {
    id: 'MOUNTAIN_BEAR',
    name: '巨型土熊',
    description: '受土遁術加持的巨型熊，攻擊力驚人。',
    stats: { maxHp: 200, atk: 20, def: 9, spd: 2 },
  },
  TEMPLE_MONK: {
    id: 'TEMPLE_MONK',
    name: '砂忍精英',
    description: '風之國砂隱村的精英忍者，善於防禦。',
    stats: { maxHp: 160, atk: 22, def: 10, spd: 6 },
    specialAbility: 'GUARD',
    specialAbilityChance: 0.3,
  },
  GUARDIAN: {
    id: 'GUARDIAN',
    name: '四尾人柱力',
    description: '四尾（孫悟空）的人柱力，擁有壓倒性的力量。',
    stats: { maxHp: 350, atk: 28, def: 12, spd: 8 },
    specialAbility: 'GUARD',
    specialAbilityChance: 0.25,
  },
  JONIN_VETERAN: {
    id: 'JONIN_VETERAN',
    name: '上忍老兵',
    description: '經驗豐富的上忍，實戰能力極強。',
    stats: { maxHp: 320, atk: 34, def: 14, spd: 9 },
  },
  SAND_PUPPETEER: {
    id: 'SAND_PUPPETEER',
    name: '砂之傀儡師',
    description: '風之國的傀儡操控師，善於防禦反擊。',
    stats: { maxHp: 270, atk: 30, def: 22, spd: 6 },
    specialAbility: 'GUARD',
    specialAbilityChance: 0.35,
  },
  ROGUE_SHINOBI: {
    id: 'ROGUE_SHINOBI',
    name: '叛忍',
    description: '脫離村莊的危險叛忍，實力強大且不擇手段。',
    stats: { maxHp: 400, atk: 40, def: 16, spd: 11 },
  },
  AKATSUKI_MEMBER: {
    id: 'AKATSUKI_MEMBER',
    name: '暁成員',
    description: '神秘組織「暁」的成員，強大到令人絕望。',
    stats: { maxHp: 550, atk: 52, def: 20, spd: 13 },
    specialAbility: 'GUARD',
    specialAbilityChance: 0.2,
  },
  ANBU_CAPTAIN: {
    id: 'ANBU_CAPTAIN',
    name: '暗部隊長',
    description: '木葉暗部的精英隊長，身手矯捷且攻守兼備。',
    stats: { maxHp: 500, atk: 48, def: 26, spd: 14 },
  },
  LEGENDARY_NINJA: {
    id: 'LEGENDARY_NINJA',
    name: '傳說忍者',
    description: '名留青史的傳說忍者，速度與力量無人能及。',
    stats: { maxHp: 450, atk: 55, def: 20, spd: 19 },
  },
  CURSED_SEAL_USER: {
    id: 'CURSED_SEAL_USER',
    name: '咒印使用者',
    description: '被大蛇丸賦予咒印之力的忍者，蓄力攻擊極為致命。',
    stats: { maxHp: 600, atk: 60, def: 22, spd: 16 },
    specialAbility: 'CHARGE',
    specialAbilityChance: 0.30,
  },
  PAIN_AVATAR: {
    id: 'PAIN_AVATAR',
    name: '天道・六道仙人',
    description: '佩恩的天道之體，掌握萬引力之術，幾乎無法抵禦。',
    stats: { maxHp: 900, atk: 70, def: 32, spd: 20 },
    specialAbility: 'GUARD',
    specialAbilityChance: 0.25,
  },
};

export const QUESTS: QuestDefinition[] = [
  {
    id: 'GRIND_QUEST',
    name: '忍者學校訓練',
    description: '擊敗 5 個替身木樁，奠定忍者基礎。',
    type: 'GRIND',
    requiredLevel: 1,
    requiredRank: 'E',
    targetEnemyId: 'TRAINING_DUMMY',
    targetCount: 5,
    reward: { exp: 50, ryo: 80 },
    repeatType: 'DAILY',
  },
  {
    id: 'WOLF_QUEST',
    name: '木葉巡邏任務',
    description: '清除 3 隻威脅村莊的追蹤忍犬。',
    type: 'GRIND',
    requiredLevel: 3,
    requiredRank: 'E',
    targetEnemyId: 'FOREST_WOLF',
    targetCount: 3,
    reward: { exp: 100, ryo: 100 },
    repeatType: 'DAILY',
  },
  {
    id: 'BANDIT_QUEST',
    name: '音忍討伐令',
    description: '擊退 2 名勒索商人的音忍刺客。',
    type: 'ELITE',
    requiredLevel: 6,
    requiredRank: 'E',
    targetEnemyId: 'BANDIT_CHIEF',
    targetCount: 2,
    reward: { exp: 170, ryo: 145 },
    repeatType: 'DAILY',
  },
  {
    id: 'ELITE_QUEST',
    name: '暗部考驗',
    description: '擊敗一名暗部隊員，證明你的實力。',
    type: 'ELITE',
    requiredLevel: 10,
    requiredRank: 'E',
    targetEnemyId: 'ELITE_NINJA',
    targetCount: 1,
    reward: { exp: 260, ryo: 200 },
    repeatType: 'DAILY',
  },
  {
    id: 'BEAR_QUEST',
    name: '土熊清剿作戰',
    description: '清除 3 隻封鎖商路的巨型土熊。',
    type: 'GRIND',
    requiredLevel: 14,
    requiredRank: 'E',
    targetEnemyId: 'MOUNTAIN_BEAR',
    targetCount: 3,
    reward: { exp: 360, ryo: 270 },
    repeatType: 'DAILY',
  },
  {
    id: 'CHUNIN_QUEST',
    name: '中忍考試預選',
    description: '擊敗 2 名暗部隊員，通過中忍考試預選。',
    type: 'ELITE',
    requiredLevel: 15,
    requiredRank: 'E',
    targetEnemyId: 'ELITE_NINJA',
    targetCount: 2,
    reward: { exp: 420, ryo: 290 },
    repeatType: 'DAILY',
  },
  {
    id: 'MONK_QUEST',
    name: '砂忍奇襲',
    description: '擊退 2 名守護被盜文物的砂忍精英。',
    type: 'ELITE',
    requiredLevel: 18,
    requiredRank: 'E',
    targetEnemyId: 'TEMPLE_MONK',
    targetCount: 2,
    reward: { exp: 460, ryo: 330 },
    repeatType: 'DAILY',
  },
  {
    id: 'ELITE2_QUEST',
    name: '暗部精英連戰',
    description: '連續擊敗 3 名暗部隊員，展示你的極限。',
    type: 'ELITE',
    requiredLevel: 22,
    requiredRank: 'E',
    targetEnemyId: 'ELITE_NINJA',
    targetCount: 3,
    reward: { exp: 560, ryo: 390 },
    repeatType: 'DAILY',
  },
  {
    id: 'BOSS_QUEST',
    name: '四尾覺醒之戰',
    description: '迎戰四尾人柱力，證明你已足夠強大晉升忍者等級。',
    type: 'BOSS',
    requiredLevel: 25,
    requiredRank: 'E',
    targetEnemyId: 'GUARDIAN',
    targetCount: 1,
    reward: { exp: 700, ryo: 500, rankExp: 1 },
    repeatType: 'ONCE',
  },
  // ── Rank D quests ─────────────────────────────────────────────────────────
  {
    id: 'D_PATROL_QUEST',
    name: '中忍巡邏任務',
    description: '擊敗 5 名上忍老兵，完成中忍巡邏任務。',
    type: 'GRIND',
    requiredLevel: 31,
    requiredRank: 'D',
    targetEnemyId: 'JONIN_VETERAN',
    targetCount: 5,
    reward: { exp: 800, ryo: 500 },
    repeatType: 'DAILY',
  },
  {
    id: 'D_PUPPET_QUEST',
    name: '傀儡師討伐令',
    description: '擊敗 2 名砂之傀儡師，清除威脅。',
    type: 'ELITE',
    requiredLevel: 36,
    requiredRank: 'D',
    targetEnemyId: 'SAND_PUPPETEER',
    targetCount: 2,
    reward: { exp: 1200, ryo: 750 },
    repeatType: 'DAILY',
  },
  {
    id: 'D_ROGUE_QUEST',
    name: '叛忍追緝令',
    description: '追蹤並擊敗 2 名叛忍，維護村莊安全。',
    type: 'ELITE',
    requiredLevel: 42,
    requiredRank: 'D',
    targetEnemyId: 'ROGUE_SHINOBI',
    targetCount: 2,
    reward: { exp: 1500, ryo: 900 },
    repeatType: 'DAILY',
  },
  {
    id: 'D_BOSS_QUEST',
    name: '暁之戰',
    description: '迎戰暁組織成員，突破極限晉升上忍。',
    type: 'BOSS',
    requiredLevel: 46,
    requiredRank: 'D',
    targetEnemyId: 'AKATSUKI_MEMBER',
    targetCount: 1,
    reward: { exp: 2500, ryo: 1500, rankExp: 1 },
    repeatType: 'ONCE',
  },
  // ── Rank C quests ─────────────────────────────────────────────────────────
  {
    id: 'C_ANBU_QUEST',
    name: '暗部精英清剿',
    description: '擊敗 5 名暗部隊長，證明上忍實力。',
    type: 'GRIND',
    requiredLevel: 51,
    requiredRank: 'C',
    targetEnemyId: 'ANBU_CAPTAIN',
    targetCount: 5,
    reward: { exp: 2000, ryo: 1000 },
    repeatType: 'DAILY',
  },
  {
    id: 'C_LEGEND_QUEST',
    name: '傳說忍者挑戰',
    description: '挑戰 2 名傳說忍者，超越前人極限。',
    type: 'ELITE',
    requiredLevel: 58,
    requiredRank: 'C',
    targetEnemyId: 'LEGENDARY_NINJA',
    targetCount: 2,
    reward: { exp: 2800, ryo: 1400 },
    repeatType: 'DAILY',
  },
  {
    id: 'C_CURSED_QUEST',
    name: '咒印者討伐',
    description: '討伐 2 名咒印使用者，封印邪惡力量。',
    type: 'ELITE',
    requiredLevel: 65,
    requiredRank: 'C',
    targetEnemyId: 'CURSED_SEAL_USER',
    targetCount: 2,
    reward: { exp: 3200, ryo: 1600 },
    repeatType: 'DAILY',
  },
  {
    id: 'C_BOSS_QUEST',
    name: '天道・六道仙人之戰',
    description: '迎戰天道佩恩，成為真正的傳說忍者。',
    type: 'BOSS',
    requiredLevel: 70,
    requiredRank: 'C',
    targetEnemyId: 'PAIN_AVATAR',
    targetCount: 1,
    reward: { exp: 5000, ryo: 3000, rankExp: 1 },
    repeatType: 'ONCE',
  },
];

export const RANKS: RankDefinition[] = [
  {
    rank: 'E',
    nextRank: 'D',
    requiredLevelCap: 30,
    requiredBossClear: true,
    bonus: { baseAtkMultiplier: 1.0, spinRarityBonus: 0 },
  },
  {
    rank: 'D',
    nextRank: 'C',
    requiredLevelCap: 50,
    requiredBossClear: true,
    bonus: { baseAtkMultiplier: 1.1, spinRarityBonus: 0.05 },
  },
  {
    rank: 'C',
    nextRank: undefined,
    requiredLevelCap: 75,
    requiredBossClear: true,
    bonus: { baseAtkMultiplier: 1.2, spinRarityBonus: 0.1 },
  },
];

export function getLevelCapForRank(rank: Rank): number {
  return RANKS.find(r => r.rank === rank)?.requiredLevelCap ?? 30;
}

// Exponential EXP curve: 100 × 1.15^(level-1)
export const EXP_PER_LEVEL = (level: number): number => Math.floor(100 * Math.pow(1.15, level - 1));
export const LEVEL_CAP = 30;
export const STAT_POINTS_PER_LEVEL = 3;
export const ATK_PER_STR = 2;
export const HP_PER_VIT = 20;
export const MD_PER_FOC = 10;

export const ITEMS: Record<string, ItemDefinition> = {
  SMALL_POTION: { id: 'SMALL_POTION', name: '小型丹藥', description: '回復30HP', type: 'POTION', price: 80, effect: { hpRestore: 30 }, usableInCombat: true, usableOutOfCombat: true },
  LARGE_POTION: { id: 'LARGE_POTION', name: '大型丹藥', description: '回復40%HP', type: 'POTION', price: 200, effect: { hpRestorePercent: 0.4 }, usableInCombat: true, usableOutOfCombat: true },
  CHAKRA_PILL: { id: 'CHAKRA_PILL', name: '查克拉藥丸', description: '回復25 Chakra', type: 'CHAKRA_PILL', price: 100, effect: { mdRestore: 25 }, usableInCombat: true, usableOutOfCombat: true },
  CHAKRA_PILL_L: { id: 'CHAKRA_PILL_L', name: '大型查克拉藥丸', description: '回復50% Chakra', type: 'CHAKRA_PILL', price: 250, effect: { mdRestorePercent: 0.5 }, usableInCombat: true, usableOutOfCombat: true },
  ATK_SCROLL: { id: 'ATK_SCROLL', name: '攻擊強化卷軸', description: '戰鬥中ATK+20%，持續5回合', type: 'SCROLL', price: 350, effect: { atkMultiplier: 1.2, buffDuration: 5 }, usableInCombat: true, usableOutOfCombat: false },
  DEF_SCROLL: { id: 'DEF_SCROLL', name: '防禦強化卷軸', description: '戰鬥中DEF+25%，持續5回合', type: 'SCROLL', price: 300, effect: { defMultiplier: 1.25, buffDuration: 5 }, usableInCombat: true, usableOutOfCombat: false },
  SPD_SCROLL: { id: 'SPD_SCROLL', name: '速度強化卷軸', description: '戰鬥中SPD+3，持續5回合', type: 'SCROLL', price: 280, effect: { spdBonus: 3, buffDuration: 5 }, usableInCombat: true, usableOutOfCombat: false },
};
