import type { BloodlineDefinition, EnemyDefinition, GearDefinition, ItemDefinition, ModeConfig, QuestDefinition, RankDefinition, Rank, SkillDefinition, SpinConfig, SkillEffectNumbers } from './types';

// Save version history:
// 1 → 2: Added completedQuestIds, freeRestUsedToday
// 2 → 3: Added inventory, activeBuffs, questResetTimestamps; migrated freeRestUsedToday → lastFreeRestDate (YYYY-MM-DD)
// 3 → 4: Added stamina/maxStamina, staminaCost on quests, playerStatusEffects in battle
// 4 → 5: Added gear system (ownedGearIds, equippedGear), lastStaminaRecovery
// 5 → 6: Added skillMasteries on player; element on bloodlines/enemies
export const SAVE_VERSION = 6;
export const MD_REGEN_BASE = 5;
export const MAX_STAMINA = 100;
export const STAMINA_REST_FREE = 50;
export const STAMINA_RECOVERY_INTERVAL_MS = 10 * 60 * 1000; // 10 minutes
export const STAMINA_RECOVERY_AMOUNT = 5; // +5 per interval

/** Display names for ranks (Naruto theme) */
export const RANK_DISPLAY: Record<Rank, string> = {
  E: '下忍 (Genin)',
  D: '中忍 (Chunin)',
  C: '上忍 (Jonin)',
};

/** Paid rest costs by level bracket */
export const CLINIC_COSTS: { maxLevel: number; cost: number }[] = [
  { maxLevel: 10, cost: 50 },
  { maxLevel: 20, cost: 120 },
  { maxLevel: 30, cost: 250 },
];

export const SKILLS: Record<string, SkillDefinition> = {
  BLAZE_SHOT: {
    id: 'BLAZE_SHOT',
    name: '火遁・豪火球之術',
    description: '發射強大火球，造成火屬性傷害並可能引燃目標。',
    hpCost: 0,
    mdCost: 15,
    cooldownTurn: 2,
    requiredLevel: 1,
    effects: {
      damageMultiplier: 1.5,
      burnChance: 0.4,
      burnDamagePerTurn: 5,
      burnDuration: 3,
    },
  },
  THUNDER_STRIKE: {
    id: 'THUNDER_STRIKE',
    name: '雷切 (Chidori)',
    description: '以閃電凝聚於手，貫穿敵人，造成巨大雷屬性傷害。',
    hpCost: 0,
    mdCost: 30,
    cooldownTurn: 4,
    requiredLevel: 8,
    effects: {
      damageMultiplier: 2.5,
    },
  },
  VOID_SLASH: {
    id: 'VOID_SLASH',
    name: '萬花筒寫輪眼・天照',
    description: '以黑炎焚盡一切，消耗 HP 和 Chakra 換取極致破壞力。',
    hpCost: 20,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 12,
    effects: {
      damageMultiplier: 3.0,
    },
  },
  IRON_GUARD: {
    id: 'IRON_GUARD',
    name: '八卦六十四掌・防禦',
    description: '以八卦掌封閉經脈，進入守護姿態，回復 15% HP。',
    hpCost: 0,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 3,
    effects: {
      damageMultiplier: 0,
      healSelfPercent: 0.15,
    },
  },
  MIST_STEP: {
    id: 'MIST_STEP',
    name: '水遁・霧隱術',
    description: '隱身濃霧中發動奇襲，回復 20 Chakra。',
    hpCost: 0,
    mdCost: 25,
    cooldownTurn: 3,
    requiredLevel: 5,
    effects: {
      damageMultiplier: 1.2,
      mdRestore: 20,
    },
  },
  WATER_DRAGON: {
    id: 'WATER_DRAGON',
    name: '水遁・水龍彈術',
    description: '召喚水龍衝擊敵人，造成強力水屬性傷害。',
    hpCost: 0,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 2,
    effects: { damageMultiplier: 2.0 },
  },
  SAND_ARMOR: {
    id: 'SAND_ARMOR',
    name: '砂瀑防護盾',
    description: '以砂包覆全身形成防護盾，回復 25% HP。',
    hpCost: 0,
    mdCost: 25,
    cooldownTurn: 4,
    requiredLevel: 4,
    effects: { damageMultiplier: 0, healSelfPercent: 0.25 },
  },
  LIGHTNING_CLONE: {
    id: 'LIGHTNING_CLONE',
    name: '雷遁・影分身',
    description: '以雷電創造分身猛攻，有機率對敵人造成灼燒。',
    hpCost: 0,
    mdCost: 25,
    cooldownTurn: 3,
    requiredLevel: 6,
    effects: { damageMultiplier: 1.8, burnChance: 0.30, burnDamagePerTurn: 6, burnDuration: 3 },
  },
  EARTH_SPIKE: {
    id: 'EARTH_SPIKE',
    name: '土遁・土流牆',
    description: '從地底升起巨大土牆衝擊敵人，造成大量傷害。',
    hpCost: 0,
    mdCost: 30,
    cooldownTurn: 4,
    requiredLevel: 10,
    effects: { damageMultiplier: 2.2 },
  },
  WIND_SLASH: {
    id: 'WIND_SLASH',
    name: '風遁・風刃術',
    description: '以風刃高速斬擊敵人，速度極快難以閃避。',
    hpCost: 0,
    mdCost: 18,
    cooldownTurn: 2,
    requiredLevel: 3,
    effects: { damageMultiplier: 1.6 },
  },
  SHADOW_BIND: {
    id: 'SHADOW_BIND',
    name: '影縫之術',
    description: '以影子束縛敵人，並趁機吸收查克拉。',
    hpCost: 0,
    mdCost: 20,
    cooldownTurn: 3,
    requiredLevel: 5,
    effects: { damageMultiplier: 1.4, mdRestore: 15 },
  },
  BONE_LANCE: {
    id: 'BONE_LANCE',
    name: '屍骨脈・骨矛',
    description: '以自身骨骼為矛貫穿敵人，消耗 HP 換取毀滅性傷害。',
    hpCost: 20,
    mdCost: 25,
    cooldownTurn: 4,
    requiredLevel: 15,
    effects: { damageMultiplier: 2.8 },
  },
  // ── Advanced nature exclusive skills ────────────────────────────────────────
  MAGNETIC_ARROW: {
    id: 'MAGNETIC_ARROW',
    name: '磁遁・砂鐵の矢',
    description: '磁遁血繼限界の奥義。砂鉄の矢を放ち、防御を無視して貫通する。',
    hpCost: 0,
    mdCost: 35,
    cooldownTurn: 5,
    requiredLevel: 20,
    effects: { damageMultiplier: 2.4, ignoreDefense: true },
  },
  SHADOW_STITCH: {
    id: 'SHADOW_STITCH',
    name: '影縫い術・奥義',
    description: '奈良一族の極意。影で敵を縫い付け、次の行動を封じる。',
    hpCost: 0,
    mdCost: 30,
    cooldownTurn: 5,
    requiredLevel: 20,
    effects: { damageMultiplier: 1.6, skipEnemyTurn: true },
  },
  BONE_THOUSAND: {
    id: 'BONE_THOUSAND',
    name: '骨槍・千本桜',
    description: '輝夜一族の奥義。骨を千の槍に変え、3回連続で攻撃する。',
    hpCost: 30,
    mdCost: 40,
    cooldownTurn: 6,
    requiredLevel: 25,
    effects: { damageMultiplier: 1.0, multiHitCount: 3 },
  },
};

export const BLOODLINES: Record<string, BloodlineDefinition> = {
  BLAZE: {
    id: 'BLAZE',
    name: '不知火一族（火遁）',
    rarity: 'COMMON',
    description: '擁有強大火遁血統，天生攻擊力提升。',
    element: 'FIRE',
    passive: { atkMultiplier: 1.1 },
    skillIds: ['BLAZE_SHOT'],
  },
  STORM: {
    id: 'STORM',
    name: '日向一族（白眼）',
    rarity: 'RARE',
    description: '白眼洞察一切弱點，提升暴擊機率。',
    element: 'LIGHTNING',
    passive: { critChanceBonus: 0.1 },
    skillIds: ['THUNDER_STRIKE'],
  },
  VOID: {
    id: 'VOID',
    name: '宇智波一族（寫輪眼）',
    rarity: 'LEGENDARY',
    description: '寫輪眼賦予極致力量，但以生命力為代價。',
    element: 'FIRE',
    passive: { atkMultiplier: 1.4, hpMultiplier: 0.8 },
    skillIds: ['VOID_SLASH'],
  },
  IRON: {
    id: 'IRON',
    name: '山中一族（鐵壁防禦）',
    rarity: 'COMMON',
    description: '山中一族的堅韌血脈，提供卓越防禦能力。',
    element: 'EARTH',
    passive: { defMultiplier: 1.25 },
    skillIds: ['IRON_GUARD'],
  },
  MIST: {
    id: 'MIST',
    name: '霧隱一族（霧步）',
    rarity: 'RARE',
    description: '霧隱忍者的血統，速度與 Chakra 回復俱佳。',
    element: 'WATER',
    passive: { spdBonus: 2, mdRegenBonus: 5 },
    skillIds: ['MIST_STEP'],
  },
  WATER: {
    id: 'WATER',
    name: '水之國族（水遁）',
    rarity: 'COMMON',
    description: '水之國的血統，查克拉回復能力優異。',
    element: 'WATER',
    passive: { mdRegenBonus: 8 },
    skillIds: ['WATER_DRAGON'],
  },
  SAND: {
    id: 'SAND',
    name: '砂之國族（防禦）',
    rarity: 'RARE',
    description: '砂隱村的防禦血統，鐵壁之守護。',
    element: 'EARTH',
    passive: { defMultiplier: 1.3, spdBonus: 1 },
    skillIds: ['SAND_ARMOR', 'MAGNETIC_ARROW'],
  },
  LIGHTNING_BL: {
    id: 'LIGHTNING_BL',
    name: '雲之村族（雷遁）',
    rarity: 'RARE',
    description: '雲隱村的雷遁血統，攻擊力與暴擊俱佳。',
    element: 'LIGHTNING',
    passive: { atkMultiplier: 1.2, critChanceBonus: 0.05 },
    skillIds: ['LIGHTNING_CLONE'],
  },
  EARTH: {
    id: 'EARTH',
    name: '岩之村族（土遁）',
    rarity: 'COMMON',
    description: '岩隱村的土遁血統，生命力強韌。',
    element: 'EARTH',
    passive: { hpMultiplier: 1.2 },
    skillIds: ['EARTH_SPIKE'],
  },
  WIND: {
    id: 'WIND',
    name: '風之國族（風遁）',
    rarity: 'COMMON',
    description: '風之國的風遁血統，速度超群。',
    element: 'WIND',
    passive: { spdBonus: 3 },
    skillIds: ['WIND_SLASH'],
  },
  SHADOW: {
    id: 'SHADOW',
    name: '奈良一族（影術）',
    rarity: 'RARE',
    description: '奈良一族的影術血統，智謀與攻擊兼備。',
    element: 'LIGHTNING',
    passive: { atkMultiplier: 1.15, critChanceBonus: 0.08 },
    skillIds: ['SHADOW_BIND', 'SHADOW_STITCH'],
  },
  KAGUYA: {
    id: 'KAGUYA',
    name: '輝夜一族（屍骨脈）',
    rarity: 'LEGENDARY',
    description: '輝夜一族的屍骨脈血統，以骨骼為武器，攻擊力強大但以生命力為代價。',
    element: 'WATER',
    passive: { atkMultiplier: 1.45, hpMultiplier: 0.85 },
    skillIds: ['BONE_LANCE', 'BONE_THOUSAND'],
  },
};

export const SPIN_CONFIG: SpinConfig = {
  priceRyo: 100,
  entries: [
    { bloodlineId: 'BLAZE', baseWeight: 50 },
    { bloodlineId: 'IRON', baseWeight: 50 },
    { bloodlineId: 'WATER', baseWeight: 50 },
    { bloodlineId: 'EARTH', baseWeight: 45 },
    { bloodlineId: 'WIND', baseWeight: 45 },
    { bloodlineId: 'STORM', baseWeight: 20 },
    { bloodlineId: 'MIST', baseWeight: 18 },
    { bloodlineId: 'SAND', baseWeight: 18 },
    { bloodlineId: 'LIGHTNING_BL', baseWeight: 15 },
    { bloodlineId: 'SHADOW', baseWeight: 15 },
    { bloodlineId: 'VOID', baseWeight: 5 },
    { bloodlineId: 'KAGUYA', baseWeight: 4 },
  ],
};

export const MODE_CONFIG: ModeConfig = {
  requiredLevel: 10,
  requireAnyBloodline: true,
  atkMultiplier: 1.5,
  defMultiplier: 1.2,
  instantHealPercent: 0.2,
  mdCostPerTurn: 10,
};

export const ENEMIES: Record<string, EnemyDefinition> = {
  TRAINING_DUMMY: {
    id: 'TRAINING_DUMMY',
    name: '替身木樁',
    description: '忍者學校的訓練用替身木樁。',
    stats: { maxHp: 50, atk: 5, def: 2, spd: 1 },
  },
  FOREST_WOLF: {
    id: 'FOREST_WOLF',
    name: '追蹤忍犬',
    description: '木葉村的追蹤忍犬，速度迅猛。',
    stats: { maxHp: 70, atk: 9, def: 3, spd: 6 },
    element: 'EARTH',
    specialAbility: 'MULTI_HIT',
    specialAbilityChance: 0.30,
  },
  BANDIT_CHIEF: {
    id: 'BANDIT_CHIEF',
    name: '音忍刺客',
    description: '大蛇丸麾下的音忍刺客，善於蓄力猛攻。',
    stats: { maxHp: 100, atk: 14, def: 4, spd: 3 },
    element: 'LIGHTNING',
    specialAbility: 'CHARGE',
    specialAbilityChance: 0.25,
  },
  ELITE_NINJA: {
    id: 'ELITE_NINJA',
    name: '暗部隊員',
    description: '木葉暗部的精銳成員，實力深不可測。',
    stats: { maxHp: 140, atk: 17, def: 6, spd: 7 },
    element: 'FIRE',
    specialAbility: 'DEBUFF',
    specialAbilityChance: 0.25,
  },
  MOUNTAIN_BEAR: {
    id: 'MOUNTAIN_BEAR',
    name: '巨型土熊',
    description: '受土遁術加持的巨型熊，攻擊力驚人。',
    stats: { maxHp: 200, atk: 20, def: 9, spd: 2 },
    element: 'EARTH',
  },
  TEMPLE_MONK: {
    id: 'TEMPLE_MONK',
    name: '砂忍精英',
    description: '風之國砂隱村的精英忍者，善於防禦。',
    stats: { maxHp: 160, atk: 22, def: 10, spd: 6 },
    element: 'WATER',
    specialAbility: 'HEAL',
    specialAbilityChance: 0.30,
  },
  GUARDIAN: {
    id: 'GUARDIAN',
    name: '四尾人柱力',
    description: '四尾（孫悟空）的人柱力，擁有壓倒性的力量。',
    stats: { maxHp: 350, atk: 28, def: 12, spd: 8 },
    element: 'FIRE',
    specialAbility: 'GUARD',
    specialAbilityChance: 0.25,
  },
  JONIN_VETERAN: {
    id: 'JONIN_VETERAN',
    name: '上忍老兵',
    description: '經驗豐富的上忍，實戰能力極強。',
    stats: { maxHp: 320, atk: 34, def: 14, spd: 9 },
    element: 'EARTH',
  },
  SAND_PUPPETEER: {
    id: 'SAND_PUPPETEER',
    name: '砂之傀儡師',
    description: '風之國的傀儡操控師，善於防禦反擊。',
    stats: { maxHp: 270, atk: 30, def: 22, spd: 6 },
    element: 'WIND',
    specialAbility: 'GUARD',
    specialAbilityChance: 0.35,
  },
  ROGUE_SHINOBI: {
    id: 'ROGUE_SHINOBI',
    name: '叛忍',
    description: '脫離村莊的危險叛忍，實力強大且不擇手段。',
    stats: { maxHp: 400, atk: 40, def: 16, spd: 11 },
    element: 'LIGHTNING',
    specialAbility: 'DEBUFF',
    specialAbilityChance: 0.25,
  },
  AKATSUKI_MEMBER: {
    id: 'AKATSUKI_MEMBER',
    name: '暁成員',
    description: '神秘組織「暁」的成員，強大到令人絕望。',
    stats: { maxHp: 550, atk: 52, def: 20, spd: 13 },
    element: 'FIRE',
    specialAbility: 'GUARD',
    specialAbilityChance: 0.2,
  },
  ANBU_CAPTAIN: {
    id: 'ANBU_CAPTAIN',
    name: '暗部隊長',
    description: '木葉暗部的精英隊長，身手矯捷且攻守兼備。',
    stats: { maxHp: 500, atk: 48, def: 26, spd: 14 },
    element: 'FIRE',
  },
  LEGENDARY_NINJA: {
    id: 'LEGENDARY_NINJA',
    name: '傳說忍者',
    description: '名留青史的傳說忍者，速度與力量無人能及。',
    stats: { maxHp: 450, atk: 55, def: 20, spd: 19 },
    element: 'WIND',
    specialAbility: 'MULTI_HIT',
    specialAbilityChance: 0.35,
  },
  CURSED_SEAL_USER: {
    id: 'CURSED_SEAL_USER',
    name: '咒印使用者',
    description: '被大蛇丸賦予咒印之力的忍者，蓄力攻擊極為致命。',
    stats: { maxHp: 600, atk: 60, def: 22, spd: 16 },
    element: 'LIGHTNING',
    specialAbility: 'CHARGE',
    specialAbilityChance: 0.30,
  },
  PAIN_AVATAR: {
    id: 'PAIN_AVATAR',
    name: '天道・六道仙人',
    description: '佩恩的天道之體，掌握萬引力之術，幾乎無法抵禦。',
    stats: { maxHp: 900, atk: 70, def: 32, spd: 20 },
    element: 'WATER',
    specialAbility: 'GUARD',
    specialAbilityChance: 0.25,
  },
};

export const QUESTS: QuestDefinition[] = [
  {
    id: 'GRIND_QUEST',
    name: '忍者學校訓練',
    description: '擊敗 5 個替身木樁，奠定忍者基礎。',
    type: 'GRIND',
    requiredLevel: 1,
    requiredRank: 'E',
    targetEnemyId: 'TRAINING_DUMMY',
    targetCount: 5,
    reward: { exp: 50, ryo: 80 },
    repeatType: 'UNLIMITED',
    staminaCost: 5,
  },
  {
    id: 'WOLF_QUEST',
    name: '木葉巡邏任務',
    description: '清除 3 隻威脅村莊的追蹤忍犬。',
    type: 'GRIND',
    requiredLevel: 3,
    requiredRank: 'E',
    targetEnemyId: 'FOREST_WOLF',
    targetCount: 3,
    reward: { exp: 100, ryo: 100 },
    repeatType: 'UNLIMITED',
    staminaCost: 5,
  },
  {
    id: 'BANDIT_QUEST',
    name: '音忍討伐令',
    description: '擊退 2 名勒索商人的音忍刺客。',
    type: 'ELITE',
    requiredLevel: 6,
    requiredRank: 'E',
    targetEnemyId: 'BANDIT_CHIEF',
    targetCount: 2,
    reward: { exp: 170, ryo: 145 },
    repeatType: 'UNLIMITED',
    staminaCost: 8,
  },
  {
    id: 'ELITE_QUEST',
    name: '暗部考驗',
    description: '擊敗一名暗部隊員，證明你的實力。',
    type: 'ELITE',
    requiredLevel: 10,
    requiredRank: 'E',
    targetEnemyId: 'ELITE_NINJA',
    targetCount: 1,
    reward: { exp: 260, ryo: 200 },
    repeatType: 'UNLIMITED',
    staminaCost: 8,
  },
  {
    id: 'BEAR_QUEST',
    name: '土熊清剿作戰',
    description: '清除 3 隻封鎖商路的巨型土熊。',
    type: 'GRIND',
    requiredLevel: 14,
    requiredRank: 'E',
    targetEnemyId: 'MOUNTAIN_BEAR',
    targetCount: 3,
    reward: { exp: 360, ryo: 270 },
    repeatType: 'UNLIMITED',
    staminaCost: 8,
  },
  {
    id: 'CHUNIN_QUEST',
    name: '中忍考試預選',
    description: '擊敗 2 名暗部隊員，通過中忍考試預選。',
    type: 'ELITE',
    requiredLevel: 15,
    requiredRank: 'E',
    targetEnemyId: 'ELITE_NINJA',
    targetCount: 2,
    reward: { exp: 420, ryo: 290 },
    repeatType: 'UNLIMITED',
    staminaCost: 10,
  },
  {
    id: 'MONK_QUEST',
    name: '砂忍奇襲',
    description: '擊退 2 名守護被盜文物的砂忍精英。',
    type: 'ELITE',
    requiredLevel: 18,
    requiredRank: 'E',
    targetEnemyId: 'TEMPLE_MONK',
    targetCount: 2,
    reward: { exp: 460, ryo: 330 },
    repeatType: 'UNLIMITED',
    staminaCost: 10,
  },
  {
    id: 'ELITE2_QUEST',
    name: '暗部精英連戰',
    description: '連續擊敗 3 名暗部隊員，展示你的極限。',
    type: 'ELITE',
    requiredLevel: 22,
    requiredRank: 'E',
    targetEnemyId: 'ELITE_NINJA',
    targetCount: 3,
    reward: { exp: 560, ryo: 390 },
    repeatType: 'UNLIMITED',
    staminaCost: 12,
  },
  {
    id: 'BOSS_QUEST',
    name: '四尾覺醒之戰',
    description: '迎戰四尾人柱力，證明你已足夠強大晉升忍者等級。',
    type: 'BOSS',
    requiredLevel: 25,
    requiredRank: 'E',
    targetEnemyId: 'GUARDIAN',
    targetCount: 1,
    reward: { exp: 700, ryo: 500, rankExp: 1 },
    repeatType: 'ONCE',
    staminaCost: 15,
  },
  // ── Rank D quests ─────────────────────────────────────────────────────────
  {
    id: 'D_PATROL_QUEST',
    name: '中忍巡邏任務',
    description: '擊敗 5 名上忍老兵，完成中忍巡邏任務。',
    type: 'GRIND',
    requiredLevel: 31,
    requiredRank: 'D',
    targetEnemyId: 'JONIN_VETERAN',
    targetCount: 5,
    reward: { exp: 800, ryo: 500 },
    repeatType: 'UNLIMITED',
    staminaCost: 8,
  },
  {
    id: 'D_PUPPET_QUEST',
    name: '傀儡師討伐令',
    description: '擊敗 2 名砂之傀儡師，清除威脅。',
    type: 'ELITE',
    requiredLevel: 36,
    requiredRank: 'D',
    targetEnemyId: 'SAND_PUPPETEER',
    targetCount: 2,
    reward: { exp: 1200, ryo: 750 },
    repeatType: 'UNLIMITED',
    staminaCost: 10,
  },
  {
    id: 'D_ROGUE_QUEST',
    name: '叛忍追緝令',
    description: '追蹤並擊敗 2 名叛忍，維護村莊安全。',
    type: 'ELITE',
    requiredLevel: 42,
    requiredRank: 'D',
    targetEnemyId: 'ROGUE_SHINOBI',
    targetCount: 2,
    reward: { exp: 1500, ryo: 900 },
    repeatType: 'UNLIMITED',
    staminaCost: 12,
  },
  {
    id: 'D_BOSS_QUEST',
    name: '暁之戰',
    description: '迎戰暁組織成員，突破極限晉升上忍。',
    type: 'BOSS',
    requiredLevel: 46,
    requiredRank: 'D',
    targetEnemyId: 'AKATSUKI_MEMBER',
    targetCount: 1,
    reward: { exp: 2500, ryo: 1500, rankExp: 1 },
    repeatType: 'ONCE',
    staminaCost: 20,
  },
  // ── Rank C quests ─────────────────────────────────────────────────────────
  {
    id: 'C_ANBU_QUEST',
    name: '暗部精英清剿',
    description: '擊敗 5 名暗部隊長，證明上忍實力。',
    type: 'GRIND',
    requiredLevel: 51,
    requiredRank: 'C',
    targetEnemyId: 'ANBU_CAPTAIN',
    targetCount: 5,
    reward: { exp: 2000, ryo: 1000 },
    repeatType: 'UNLIMITED',
    staminaCost: 12,
  },
  {
    id: 'C_LEGEND_QUEST',
    name: '傳說忍者挑戰',
    description: '挑戰 2 名傳說忍者，超越前人極限。',
    type: 'ELITE',
    requiredLevel: 58,
    requiredRank: 'C',
    targetEnemyId: 'LEGENDARY_NINJA',
    targetCount: 2,
    reward: { exp: 2800, ryo: 1400 },
    repeatType: 'UNLIMITED',
    staminaCost: 15,
  },
  {
    id: 'C_CURSED_QUEST',
    name: '咒印者討伐',
    description: '討伐 2 名咒印使用者，封印邪惡力量。',
    type: 'ELITE',
    requiredLevel: 65,
    requiredRank: 'C',
    targetEnemyId: 'CURSED_SEAL_USER',
    targetCount: 2,
    reward: { exp: 3200, ryo: 1600 },
    repeatType: 'UNLIMITED',
    staminaCost: 18,
  },
  {
    id: 'C_BOSS_QUEST',
    name: '天道・六道仙人之戰',
    description: '迎戰天道佩恩，成為真正的傳說忍者。',
    type: 'BOSS',
    requiredLevel: 70,
    requiredRank: 'C',
    targetEnemyId: 'PAIN_AVATAR',
    targetCount: 1,
    reward: { exp: 5000, ryo: 3000, rankExp: 1 },
    repeatType: 'ONCE',
    staminaCost: 25,
  },
];

export const RANKS: RankDefinition[] = [
  {
    rank: 'E',
    nextRank: 'D',
    requiredLevelCap: 30,
    requiredBossClear: true,
    bonus: { baseAtkMultiplier: 1.0, spinRarityBonus: 0 },
  },
  {
    rank: 'D',
    nextRank: 'C',
    requiredLevelCap: 50,
    requiredBossClear: true,
    bonus: { baseAtkMultiplier: 1.1, spinRarityBonus: 0.05 },
  },
  {
    rank: 'C',
    nextRank: undefined,
    requiredLevelCap: 75,
    requiredBossClear: true,
    bonus: { baseAtkMultiplier: 1.2, spinRarityBonus: 0.1 },
  },
];

export function getLevelCapForRank(rank: Rank): number {
  return RANKS.find(r => r.rank === rank)?.requiredLevelCap ?? 30;
}

// Exponential EXP curve: 100 × 1.15^(level-1)
export const EXP_PER_LEVEL = (level: number): number => Math.floor(100 * Math.pow(1.15, level - 1));
export const LEVEL_CAP = 30;
export const STAT_POINTS_PER_LEVEL = 3;
export const ATK_PER_STR = 2;
export const HP_PER_VIT = 20;
export const MD_PER_FOC = 10;

export const RARE_BLOODLINE_IDS = ['STORM', 'MIST', 'VOID', 'SAND', 'LIGHTNING_BL', 'SHADOW', 'KAGUYA'];

export const ITEMS: Record<string, ItemDefinition> = {
  SMALL_POTION: { id: 'SMALL_POTION', name: '小型丹藥', description: '回復30HP', type: 'POTION', price: 80, effect: { hpRestore: 30 }, usableInCombat: true, usableOutOfCombat: true },
  LARGE_POTION: { id: 'LARGE_POTION', name: '大型丹藥', description: '回復40%HP', type: 'POTION', price: 200, effect: { hpRestorePercent: 0.4 }, usableInCombat: true, usableOutOfCombat: true },
  CHAKRA_PILL: { id: 'CHAKRA_PILL', name: '查克拉藥丸', description: '回復25 Chakra', type: 'CHAKRA_PILL', price: 100, effect: { mdRestore: 25 }, usableInCombat: true, usableOutOfCombat: true },
  CHAKRA_PILL_L: { id: 'CHAKRA_PILL_L', name: '大型查克拉藥丸', description: '回復50% Chakra', type: 'CHAKRA_PILL', price: 250, effect: { mdRestorePercent: 0.5 }, usableInCombat: true, usableOutOfCombat: true },
  ATK_SCROLL: { id: 'ATK_SCROLL', name: '攻擊強化卷軸', description: '戰鬥中ATK+20%，持續5回合', type: 'SCROLL', price: 350, effect: { atkMultiplier: 1.2, buffDuration: 5 }, usableInCombat: true, usableOutOfCombat: false },
  DEF_SCROLL: { id: 'DEF_SCROLL', name: '防禦強化卷軸', description: '戰鬥中DEF+25%，持續5回合', type: 'SCROLL', price: 300, effect: { defMultiplier: 1.25, buffDuration: 5 }, usableInCombat: true, usableOutOfCombat: false },
  SPD_SCROLL: { id: 'SPD_SCROLL', name: '速度強化卷軸', description: '戰鬥中SPD+3，持續5回合', type: 'SCROLL', price: 280, effect: { spdBonus: 3, buffDuration: 5 }, usableInCombat: true, usableOutOfCombat: false },
  STAMINA_PILL: { id: 'STAMINA_PILL', name: '精力丹', description: '恢復 30 精力', type: 'POTION', price: 120, effect: { staminaRestore: 30 }, usableInCombat: false, usableOutOfCombat: true },
};

export const QUEST_ZONES: { zone: string; emoji: string; questIds: string[] }[] = [
  { zone: '木葉忍者學校', emoji: '🏫', questIds: ['GRIND_QUEST', 'WOLF_QUEST'] },
  { zone: '音忍邊境', emoji: '🎵', questIds: ['BANDIT_QUEST'] },
  { zone: '木葉暗部道場', emoji: '🌿', questIds: ['ELITE_QUEST', 'CHUNIN_QUEST', 'ELITE2_QUEST'] },
  { zone: '山中通道', emoji: '🏔️', questIds: ['BEAR_QUEST', 'MONK_QUEST'] },
  { zone: '最終試煉', emoji: '🌀', questIds: ['BOSS_QUEST'] },
  { zone: '中忍領域', emoji: '🏯', questIds: ['D_PATROL_QUEST', 'D_PUPPET_QUEST', 'D_ROGUE_QUEST', 'D_BOSS_QUEST'] },
  { zone: '上忍領域', emoji: '⚔️', questIds: ['C_ANBU_QUEST', 'C_LEGEND_QUEST', 'C_CURSED_QUEST', 'C_BOSS_QUEST'] },
];

export const GEAR: Record<string, GearDefinition> = {
  STARTER_SWORD: {
    id: 'STARTER_SWORD',
    name: '木葉標準刀',
    description: '木葉村下忍標準裝備，基礎攻擊力提升。',
    slot: 'WEAPON',
    rarity: 'COMMON',
    price: 200,
    stats: { atkBonus: 5 },
  },
  WIND_BLADE: {
    id: 'WIND_BLADE',
    name: '追風刃',
    description: '以風遁查克拉強化的刀刃，攻擊力大幅提升。',
    slot: 'WEAPON',
    rarity: 'RARE',
    price: 600,
    stats: { atkBonus: 14 },
  },
  THUNDER_FANG: {
    id: 'THUNDER_FANG',
    name: '雷牙',
    description: '以雷遁凝聚的傳說兵器，攻擊力極強。',
    slot: 'WEAPON',
    rarity: 'LEGENDARY',
    price: 2000,
    stats: { atkBonus: 28 },
  },
  TRAINING_ROBE: {
    id: 'TRAINING_ROBE',
    name: '訓練道服',
    description: '標準忍者道服，提供基本防禦。',
    slot: 'ARMOR',
    rarity: 'COMMON',
    price: 200,
    stats: { defBonus: 5 },
  },
  ANBU_ARMOR: {
    id: 'ANBU_ARMOR',
    name: '暗部護甲',
    description: '木葉暗部的精鍛護甲，攻守兼備。',
    slot: 'ARMOR',
    rarity: 'RARE',
    price: 800,
    stats: { defBonus: 12, hpBonus: 30 },
  },
  SAGE_COAT: {
    id: 'SAGE_COAT',
    name: '仙人外套',
    description: '傳說仙人的戰甲，每回合自動回復少量HP。',
    slot: 'ARMOR',
    rarity: 'LEGENDARY',
    price: 2500,
    stats: { defBonus: 20, hpBonus: 60, hpRegenPerTurn: 3 },
  },
  CHAKRA_BEAD: {
    id: 'CHAKRA_BEAD',
    name: '查克拉珠',
    description: '查克拉充沛的念珠，戰鬥中加快查克拉回復。',
    slot: 'ACCESSORY',
    rarity: 'COMMON',
    price: 300,
    stats: { mdRegenBonus: 8 },
  },
  SPEED_SEAL: {
    id: 'SPEED_SEAL',
    name: '速度封印',
    description: '印刻在皮膚上的速度封印，大幅提升移動速度。',
    slot: 'ACCESSORY',
    rarity: 'RARE',
    price: 700,
    stats: { spdBonus: 4 },
  },
  LIFE_CHARM: {
    id: 'LIFE_CHARM',
    name: '生命護符',
    description: '充滿生命力的護符，每回合被動回復 HP。',
    slot: 'ACCESSORY',
    rarity: 'LEGENDARY',
    price: 1800,
    stats: { hpRegenPerTurn: 5, hpBonus: 40 },
  },
};

export const GEAR_SHOP_IDS: string[] = [
  'STARTER_SWORD', 'WIND_BLADE', 'THUNDER_FANG',
  'TRAINING_ROBE', 'ANBU_ARMOR', 'SAGE_COAT',
  'CHAKRA_BEAD', 'SPEED_SEAL', 'LIFE_CHARM',
];

export interface SkillTierDefinition {
  name: string;
  description: string;
  effects: SkillEffectNumbers;
  mdCost?: number;
  hpCost?: number;
  cooldownTurn?: number;
}

export const SKILL_TIERS: Record<string, { kai?: SkillTierDefinition; ougi?: SkillTierDefinition }> = {
  BLAZE_SHOT: {
    kai: {
      name: '火遁・豪火球 改',
      description: '改良版豪火球の術。炎の持続時間が延長される。',
      effects: { damageMultiplier: 1.5, burnChance: 0.4, burnDamagePerTurn: 5, burnDuration: 5 },
    },
    ougi: {
      name: '火遁・真空波',
      description: '奥義：爆炎の波動を放ち、圧倒的な火属性ダメージを与える。',
      effects: { damageMultiplier: 2.8, burnChance: 0.6, burnDamagePerTurn: 8, burnDuration: 4 },
    },
  },
  THUNDER_STRIKE: {
    kai: {
      name: '雷切流',
      description: '雷切の改良型。速度低下効果が付与される。',
      effects: { damageMultiplier: 2.5, spdDebuff: true },
    },
    ougi: {
      name: '紫電',
      description: '奥義：紫の稲妻で敵を貫き、麻痺を与える。',
      effects: { damageMultiplier: 3.5, skipEnemyTurn: true },
      mdCost: 40,
    },
  },
  VOID_SLASH: {
    kai: {
      name: '天照 改',
      description: '天照の改良型。HP消費が軽減される。',
      effects: { damageMultiplier: 3.0 },
      hpCost: 10,
      mdCost: 20,
    },
    ougi: {
      name: '須佐能乎',
      description: '奥義：完全体須佐能乎を発動。次の敵の攻撃を30%反射する。',
      effects: { damageMultiplier: 4.0, reflectDamagePercent: 0.3 },
      hpCost: 25,
      mdCost: 30,
    },
  },
  IRON_GUARD: {
    kai: {
      name: '八卦六十四掌・改',
      description: '改良版八卦掌。回復量が増加する。',
      effects: { damageMultiplier: 0, healSelfPercent: 0.25 },
    },
    ougi: {
      name: '八卦空掌',
      description: '奥義：次の敵の攻撃を完全に反射する。',
      effects: { damageMultiplier: 0, healSelfPercent: 0.25, reflectDamagePercent: 0.5 },
    },
  },
  MIST_STEP: {
    kai: {
      name: '水遁・霧隠し 改',
      description: '改良版霧隠し。Chakra回復量が増加する。',
      effects: { damageMultiplier: 1.4, mdRestore: 30 },
    },
    ougi: {
      name: '幻霧殺',
      description: '奥義：霧の幻惑で敵の次の行動を封じる。',
      effects: { damageMultiplier: 2.0, mdRestore: 20, skipEnemyTurn: true },
    },
  },
  WATER_DRAGON: {
    kai: {
      name: '水遁・水龍弾 改',
      description: '水龍の力が増大し、より多くのダメージを与える。',
      effects: { damageMultiplier: 2.5 },
    },
    ougi: {
      name: '水遁・大爆流',
      description: '奥義：巨大な水流で敵を押し流す。',
      effects: { damageMultiplier: 3.5 },
    },
  },
  SAND_ARMOR: {
    kai: {
      name: '砂瀑防護盾 改',
      description: '改良版砂防護。回復量が増加する。',
      effects: { damageMultiplier: 0, healSelfPercent: 0.35 },
    },
    ougi: {
      name: '絶対防御',
      description: '奥義：砂で完全に身を包み、次のダメージを50%軽減しつつ回復する。',
      effects: { damageMultiplier: 0, healSelfPercent: 0.4, reflectDamagePercent: 0.2 },
    },
  },
  LIGHTNING_CLONE: {
    kai: {
      name: '雷遁・影分身 改',
      description: '分身の雷力が増強。燃焼確率が上昇する。',
      effects: { damageMultiplier: 2.2, burnChance: 0.45, burnDamagePerTurn: 8, burnDuration: 3 },
    },
    ougi: {
      name: '雷神の術',
      description: '奥義：雷の化身となり、圧倒的な電撃を放つ。',
      effects: { damageMultiplier: 3.2, burnChance: 0.6, burnDamagePerTurn: 10, burnDuration: 4 },
    },
  },
  EARTH_SPIKE: {
    kai: {
      name: '土遁・土流壁 改',
      description: '改良版土流壁。より強力な衝撃を与える。',
      effects: { damageMultiplier: 2.8 },
    },
    ougi: {
      name: '土遁・岩石激流',
      description: '奥義：大地を操り岩石の津波を起こす。',
      effects: { damageMultiplier: 3.8 },
      mdCost: 40,
    },
  },
  WIND_SLASH: {
    kai: {
      name: '風遁・風刃術 改',
      description: '改良版風刃術。切れ味が増し、ダメージが向上する。',
      effects: { damageMultiplier: 2.0 },
    },
    ougi: {
      name: '風遁・真空波',
      description: '奥義：真空の刃で敵を切り裂く。',
      effects: { damageMultiplier: 3.0 },
    },
  },
  SHADOW_BIND: {
    kai: {
      name: '影縫い術 改',
      description: '影縫いの精度が上昇。Chakra吸収量が増える。',
      effects: { damageMultiplier: 1.8, mdRestore: 25 },
    },
    ougi: {
      name: '影真似の術・完全体',
      description: '奥義：完全な影模倣で敵を完全拘束する。',
      effects: { damageMultiplier: 2.4, mdRestore: 20, skipEnemyTurn: true },
    },
  },
  BONE_LANCE: {
    kai: {
      name: '屍骨脈・骨矛 改',
      description: '骨矛の貫通力が向上する。HP消費が軽減される。',
      effects: { damageMultiplier: 2.8 },
      hpCost: 12,
      mdCost: 25,
    },
    ougi: {
      name: '屍骨脈・舞',
      description: '奥義：屍骨脈の究極奥義。骨を全身から放出し圧倒的ダメージを与える。',
      effects: { damageMultiplier: 4.0 },
      hpCost: 20,
      mdCost: 35,
    },
  },
};
